### ISSUE TITLE
Django 1.10 compatibillity issue with extract_keys

### ISSUE THREAD

**Issue by mikaelengstrom** [dreipol/django-scarface#19]
When running the extract_keys command i get the following error:
```
Traceback (most recent call last):
  File "./manage.py", line 24, in <module>
    execute_from_command_line(sys.argv)
  File "/usr/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 367, in execute_from_command_line
    utility.execute()
  File "/usr/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 359, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/usr/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 208, in fetch_command
    klass = load_command_class(app_name, subcommand)
  File "/usr/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 40, in load_command_class
    module = import_module('%s.management.commands.%s' % (app_name, name))
  File "/usr/local/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/usr/local/lib/python2.7/site-packages/scarface/management/commands/extract_keys.py", line 16, in <module>
    class Command(BaseCommand):
  File "/usr/local/lib/python2.7/site-packages/scarface/management/commands/extract_keys.py", line 17, in Command
    option_list = BaseCommand.option_list + (
AttributeError: type object 'BaseCommand' has no attribute 'option_list'
```

option_list have been deprecated since Django 1.8. [BaseCommand.add_arguments](https://docs.djangoproject.com/en/1.10/howto/custom-management-commands/#django.core.management.BaseCommand.add_arguments) should be used instead.

**Comment by mikaelengstrom** [comment]
Noticed this pull request which seem to solve it: https://github.com/dreipol/django-scarface/pull/18

Could you please merge it?

**Comment by nanorepublica** [comment]
FYI: #18 has now been merged.

**Comment by melbic** [comment]
True that, I therefor close this issue. Thanks @nanorepublica.
