### ISSUE TITLE
Can't install django-scarface 3.2

### ISSUE THREAD

**Issue by karltaylor** [dreipol/django-scarface#31]
I'm having trouble installing django-scarface 3.2. I am not sure if this is a django-scarface problem but any help would be great.

```python
pip install django-scarface
```

```python
Collecting django-scarface
  Using cached https://files.pythonhosted.org/packages/c6/ba/ceae41786d0e3de3e0e33cf503c663cd47e0921e5893194f5c5000acba15/django-scarface-3.2.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/private/var/folders/y6/y3twpy9557xb2d9mvwpcymh00000gn/T/pip-install-e2xdk8fn/django-scarface/setup.py", line 31, in <module>
        version=get_version("django_scarface", "__init__.py"),
      File "/private/var/folders/y6/y3twpy9557xb2d9mvwpcymh00000gn/T/pip-install-e2xdk8fn/django-scarface/setup.py", line 21, in get_version
        version_file = open(filename).read()
    FileNotFoundError: [Errno 2] No such file or directory: '/private/var/folders/y6/y3twpy9557xb2d9mvwpcymh00000gn/T/pip-install-e2xdk8fn/django-scarface/django_scarface/__init__.py'
```

**Comment by melbic** [comment]
I was able to reproduce the problem and pushed a new version 3.2.1 please install this one.
